### ISSUE TITLE
v3载入插件失败

### ISSUE THREAD

**Issue by 127Wzc** [snowtafir/yuki-plugin#1]
当前版本:
```
commit 8826afcd9be938cabd3f645efb83eec6256026cc (HEAD -> main3, origin/main3)
Author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
Date:   2024-08-07 13:50:26

    fix DYNAMIC_TYPE_FORWARD
```
载入失败异常日志：
<img width="1173" alt="image" src="https://github.com/user-attachments/assets/97e56b75-6768-4c54-8a0d-ed5648fb7891">

**Comment by snowtafir** [comment]
> 当前版本:
> 
> ```
> commit 8826afcd9be938cabd3f645efb83eec6256026cc (HEAD -> main3, origin/main3)
> Author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
> Date:   2024-08-07 13:50:26
> 
>     fix DYNAMIC_TYPE_FORWARD
> ```
> 
> 载入失败异常日志： <img alt="image" width="1173" src="https://private-user-images.githubusercontent.com/52766844/355862132-97e56b75-6768-4c54-8a0d-ed5648fb7891.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwOTYxMTQsIm5iZiI6MTcyMzA5NTgxNCwicGF0aCI6Ii81Mjc2Njg0NC8zNTU4NjIxMzItOTdlNTZiNzUtNjc2OC00YzU0LThhMGQtZWQ1NjQ4ZmI3ODkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA1NDMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExNTBlYWEzYmY0ZjRiY2M4ZWQwYWY2NDgxN2RjZjRmZDc3MzViMGE5MjQzNzZiNDJmOTc2OTNhOTI3MTc2MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GC9k_BJGTQEyAg1W0GoyFZM8Z4SVeN0GG9b6YCYLU3g">

已修复 ，私聊bot发送 #强制更新yuki-plugin 即可，记得更新依赖： pnpm i
