### ISSUE TITLE
希望在配置文件里面增加一个可以选择推送的时候是否艾特全体的配置项

### ISSUE THREAD

**Issue by xiaofei114** [snowtafir/yuki-plugin#10]
希望在配置文件里面增加一个可以选择推送的时候是否艾特全体的配置项

**Comment by snowtafir** [comment]
> 希望在配置文件里面增加一个可以选择推送的时候是否艾特全体的配置项

艾特全体成员有次数限制，比如qq每日10次。动态一多就很快失效。没大意义

**Comment by xiaofei114** [comment]
> > 希望在配置文件里面增加一个可以选择推送的时候是否艾特全体的配置项
> 
> 艾特全体成员有次数限制，比如qq每日10次。动态一多就很快失效。没大意义

那如果设置成特定的东西艾特全体呢，直播总不可能一天播10次吧

**Comment by CICILC** [comment]
可以曲线救国 关掉机器人的自身消息过滤 然后添加直播推送内容为关键词 回复艾特全体
