### ISSUE TITLE
功能建议：B站视频收录功能

### ISSUE THREAD

**Issue by CICILC** [snowtafir/yuki-plugin#11]
我再提一个大胆的建议（不强求 能实现则十分感谢）

功能描述：对群友发的B站链接进行收录 在需要调用的时候返回最近群里发的B站视频链接

背景：因为群友经常喜欢分享一些B站视频 虽然有解析或者下载 但是因为时间问题不能立马观看 但是晚上回家以后想看又很难找到今天都发了哪些B站视频 所以想着能不能搞一个识别B站链接自动记录 然后有需要的时候返回今日发送过的视频链接

可能的实现方法：由于判断是否已经看过这条视频比较麻烦 所以可以简化成每次查询只回复最近的5条B站链接 收录也很简单 识别B站链接就写入文件或者怎么样 

效果：虽然只回复最近5条 但是基本能满足80%的需求 总比一条都不看要好 

展望：要是能更进一步弄个分类收藏夹也不错

**Comment by snowtafir** [comment]
> 我再提一个大胆的建议（不强求 能实现则十分感谢）
> 
> 功能描述：对群友发的B站链接进行收录 在需要调用的时候返回最近群里发的B站视频链接
> 
> 背景：因为群友经常喜欢分享一些B站视频 虽然有解析或者下载 但是因为时间问题不能立马观看 但是晚上回家以后想看又很难找到今天都发了哪些B站视频 所以想着能不能搞一个识别B站链接自动记录 然后有需要的时候返回今日发送过的视频链接
> 
> 可能的实现方法：由于判断是否已经看过这条视频比较麻烦 所以可以简化成每次查询只回复最近的5条B站链接 收录也很简单 识别B站链接就写入文件或者怎么样
> 
> 效果：虽然只回复最近5条 但是基本能满足80%的需求 总比一条都不看要好
> 
> 展望：要是能更进一步弄个分类收藏夹也不错

此功能跟订阅动态相关性过小，不考虑添加。
建议单独编写一个单js插件放到 `Yunzai/plugins/example/` 即可实现所需功能。到插件库找一个足够简单的可用的js插件，按照格式魔改即可，具体拆分的步骤如何实现，如果不会编程，可以问gpt或使用相关AI工具辅助
