### ISSUE TITLE
多个群订阅同一个up有些群推送有些群不推送

### ISSUE THREAD

**Issue by CICILC** [snowtafir/yuki-plugin#12]
多个群订阅同一个up有些群推送有些群不推送
![fd5215d419702c9fa7852f43841b311e](https://github.com/user-attachments/assets/a5c1e06b-6ebf-4d60-899f-5744641a75e2)
![image](https://github.com/user-attachments/assets/9591b6d9-b198-4325-a449-33080cfd1644)
![image](https://github.com/user-attachments/assets/741db9b4-493e-4b9b-8f43-9ea07318280d)
只有一个群推了 其他订阅这个up的群都没消息 强制更新+重新添加订阅过也是这样 有可能是什么原因呀

**Comment by CICILC** [comment]
过了10分钟使用#执行B站任务 就又推送了 不知道是一轮只会推一个群还是什么原因（没有等到第二轮的23分种后）

**Comment by snowtafir** [comment]
> 过了10分钟使用#执行B站任务 就又推送了 不知道是一轮只会推一个群还是什么原因（没有等到第二轮的23分种后）

你触发风控了。更新试试

**Comment by CICILC** [comment]
我调成30分钟检测一次了（原23分钟）可以看到不风控了 但是为了保险起见我只给一个群推送了 稍后我会测试给多个群推送 
但是话说回来了 按理来说有一个群推送了应该是B站方面没问题反而是qq风控才会出现这种情况（显然不是qq被风控） 如果B站风控了应该是所有群都不能推送才对
