### ISSUE TITLE
可以不推送转发的动态吗

### ISSUE THREAD

**Issue by 34200501** [snowtafir/yuki-plugin#3]
有时候抽奖的转发有点扰人，寻思从闲心迁过来的是不是可以选择开关推送转发？

**Comment by snowtafir** [comment]
> 有时候抽奖的转发有点扰人，寻思从闲心迁过来的是不是可以选择开关推送转发？

分类订阅，单个up订阅除了转发的就行，或者配置文件关掉所有转发

**Comment by 34200501** [comment]
> > 有时候抽奖的转发有点扰人，寻思从闲心迁过来的是不是可以选择开关推送转发？
> 
> 分类订阅，单个up订阅除了转发的就行，或者配置文件关掉所有转发

感谢解答
