### ISSUE TITLE
trss-yunzai，yuki帮助和微博推送报错

### ISSUE THREAD

**Issue by Chocolatemocha** [snowtafir/yuki-plugin#4]
trss-yunzai V3.1.3，且启动时优纪插件没有报错；
在执行 手动推送微博 和 获取优纪插件帮助 时报错,正常等待微博也没有推送，也是这样的报错。
报错信息是api code-60以及下图，请大佬看下这是yunzai本体我哪里配置错误的原因，还是插件哪里需要我自行改下配置呢？
（同样是匿名转发消息的本体#日志/#错误日志等没有报错正常发送，且已经执行了更新sign签名脚本操作）；
![image](https://github.com/user-attachments/assets/2c46ecef-d1fa-476f-b851-7d1b040378a5)
![image](https://github.com/user-attachments/assets/b4d81f8c-64ff-4c8f-9de9-e83470888db0)
![image](https://github.com/user-attachments/assets/86fea19f-c85a-4fa0-b3f7-ef214db69181)

**Comment by snowtafir** [comment]
> trss-yunzai V3.1.3，且启动时优纪插件没有报错； 在执行 手动推送微博 和 获取优纪插件帮助 时报错,正常等待微博也没有推送，也是这样的报错。 报错信息是api code-60以及下图，请大佬看下这是yunzai本体我哪里配置错误的原因，还是插件哪里需要我自行改下配置呢？ （同样是匿名转发消息的本体#日志/#错误日志等没有报错正常发送，且已经执行了更新sign签名脚本操作）； ![image](https://private-user-images.githubusercontent.com/42531322/359766030-2c46ecef-d1fa-476f-b851-7d1b040378a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyOTQ4NzksIm5iZiI6MTcyNDI5NDU3OSwicGF0aCI6Ii80MjUzMTMyMi8zNTk3NjYwMzAtMmM0NmVjZWYtZDFmYS00NzZmLWI4NTEtN2QxYjA0MDM3OGE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDAyNDI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyYzY1ZWFkODE4ZGQ1MDVmZTJhYzRiYjQ0ZDcwYjdkNmU3ODg4MjJlMWY3MDFjNjU3Y2JjNjAyMjMwMGI0MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3qa-uQaFHtcdgiHnJJNE4eh269LWMIo8HgSTEotjFXk) ![image](https://private-user-images.githubusercontent.com/42531322/359766337-b4d81f8c-64ff-4c8f-9de9-e83470888db0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyOTQ4NzksIm5iZiI6MTcyNDI5NDU3OSwicGF0aCI6Ii80MjUzMTMyMi8zNTk3NjYzMzctYjRkODFmOGMtNjRmZi00YzhmLTlkZTktZTgzNDcwODg4ZGIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDAyNDI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNDEwNjQ1YTg3MTc1ODhlNWNlYTQ5NTVmMzgxNjUxODg1MTc1ODZlZWE3NjdkZmY1YzIzM2VhYjY4ZGYzZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0XccFDq_B6VYNuK5RFX0QzgYM6Lp0gZxr1aVzy9N_bM) ![image](https://private-user-images.githubusercontent.com/42531322/359766470-86fea19f-c85a-4fa0-b3f7-ef214db69181.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyOTQ4NzksIm5iZiI6MTcyNDI5NDU3OSwicGF0aCI6Ii80MjUzMTMyMi8zNTk3NjY0NzAtODZmZWExOWYtYzg1YS00ZmEwLWIzZjctZWYyMTRkYjY5MTgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDAyNDI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5MjljNTZlMGVmYWY5MTYwZWQxNGQ3MGEyZDEwNTAyMjJiMDQ4MTg4NGEwNTYyNzdlYzJhZTkyNzg5M2IxZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7X02kfRs_Vda1vDyfQlGQykqIZyuGifovAbTjmL-jOg)
这是新版puppeteer搞的鬼，最新版本已修复

**Comment by Chocolatemocha** [comment]
> > trss-yunzai V3.1.3，且启动时优纪插件没有报错； 在执行 手动推送微博 和 获取优纪插件帮助 时报错,正常等待微博也没有推送，也是这样的报错。 报错信息是api code-60以及下图，请大佬看下这是yunzai本体我哪里配置错误的原因，还是插件哪里需要我自行改下配置呢？ （同样是匿名转发消息的本体#日志/#错误日志等没有报错正常发送，且已经执行了更新sign签名脚本操作）； ![image](https://private-user-images.githubusercontent.com/42531322/359766030-2c46ecef-d1fa-476f-b851-7d1b040378a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyOTQ4NzksIm5iZiI6MTcyNDI5NDU3OSwicGF0aCI6Ii80MjUzMTMyMi8zNTk3NjYwMzAtMmM0NmVjZWYtZDFmYS00NzZmLWI4NTEtN2QxYjA0MDM3OGE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDAyNDI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyYzY1ZWFkODE4ZGQ1MDVmZTJhYzRiYjQ0ZDcwYjdkNmU3ODg4MjJlMWY3MDFjNjU3Y2JjNjAyMjMwMGI0MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3qa-uQaFHtcdgiHnJJNE4eh269LWMIo8HgSTEotjFXk) ![image](https://private-user-images.githubusercontent.com/42531322/359766337-b4d81f8c-64ff-4c8f-9de9-e83470888db0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyOTQ4NzksIm5iZiI6MTcyNDI5NDU3OSwicGF0aCI6Ii80MjUzMTMyMi8zNTk3NjYzMzctYjRkODFmOGMtNjRmZi00YzhmLTlkZTktZTgzNDcwODg4ZGIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDAyNDI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNDEwNjQ1YTg3MTc1ODhlNWNlYTQ5NTVmMzgxNjUxODg1MTc1ODZlZWE3NjdkZmY1YzIzM2VhYjY4ZGYzZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0XccFDq_B6VYNuK5RFX0QzgYM6Lp0gZxr1aVzy9N_bM) ![image](https://private-user-images.githubusercontent.com/42531322/359766470-86fea19f-c85a-4fa0-b3f7-ef214db69181.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyOTQ4NzksIm5iZiI6MTcyNDI5NDU3OSwicGF0aCI6Ii80MjUzMTMyMi8zNTk3NjY0NzAtODZmZWExOWYtYzg1YS00ZmEwLWIzZjctZWYyMTRkYjY5MTgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDAyNDI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5MjljNTZlMGVmYWY5MTYwZWQxNGQ3MGEyZDEwNTAyMjJiMDQ4MTg4NGEwNTYyNzdlYzJhZTkyNzg5M2IxZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7X02kfRs_Vda1vDyfQlGQykqIZyuGifovAbTjmL-jOg)
> 
> 这是新版puppeteer搞的鬼，最新版本已修复

明白了，谢谢大佬

**Comment by Chocolatemocha** [comment]
已通过降级崽本体puppeteer版本为22.13.1解决，推送和帮助均恢复正常。
