### ISSUE TITLE
Linux未出现config文件夹却能正常使用

### ISSUE THREAD

**Issue by devil233-ui** [snowtafir/yuki-plugin#5]
抱歉抱歉，是我想当然把配置文件路径当成和闲心一样了。没去展开readme的指令列表也是因为直接用了`yuki帮助`……或许建议可以把路径不要折叠在指令里面？

也不对啊，重新看了下，我win服务器的配置文件路径还是在插件而非崽下面；是因为喵崽的关系吗？但我很早就通过`node trss`一键迁移了
![image](https://github.com/user-attachments/assets/1110f2ff-e463-4441-a5bb-abc120a9d046)

**Comment by snowtafir** [comment]
> 抱歉抱歉，是我想当然把配置文件路径当成和闲心一样了。没去展开readme的指令列表也是因为直接用了`yuki帮助`……或许建议可以把路径不要折叠在指令里面？
> 
> 也不对啊，重新看了下，我win服务器的配置文件路径还是在插件而非崽下面；是因为喵崽的关系吗？但我很早就通过`node trss`一键迁移了 ![image](https://private-user-images.githubusercontent.com/69190444/362302646-1110f2ff-e463-4441-a5bb-abc120a9d046.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4Njk4NjcsIm5iZiI6MTcyNDg2OTU2NywicGF0aCI6Ii82OTE5MDQ0NC8zNjIzMDI2NDYtMTExMGYyZmYtZTQ2My00NDQxLWE1YmItYWJjMTIwYTlkMDQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDE4MjYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2OTA5YmMzMzczNDNmMTAxNGJmMGE5YzMzZTg0ZGJkNmRjNmQzYTUyOGRlNDc5Zjg3Mzc3ZTJhZGM4NThjNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F8sTlNG_Kfo0ycT0-lNqL8Grxm826unQJmcLk-H5tf4)

最新版本配置文件统一为 `yunzai/data/yuki-plugin/config/` 更新完重启后看看。旧的不会自动删除，只是不会读取它

**Comment by devil233-ui** [comment]
> > 抱歉抱歉，是我想当然把配置文件路径当成和闲心一样了。没去展开readme的指令列表也是因为直接用了`yuki帮助`……或许建议可以把路径不要折叠在指令里面？
> > 也不对啊，重新看了下，我win服务器的配置文件路径还是在插件而非崽下面；是因为喵崽的关系吗？但我很早就通过`node trss`一键迁移了 ![image](https://private-user-images.githubusercontent.com/69190444/362302646-1110f2ff-e463-4441-a5bb-abc120a9d046.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4Njk4NjcsIm5iZiI6MTcyNDg2OTU2NywicGF0aCI6Ii82OTE5MDQ0NC8zNjIzMDI2NDYtMTExMGYyZmYtZTQ2My00NDQxLWE1YmItYWJjMTIwYTlkMDQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDE4MjYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2OTA5YmMzMzczNDNmMTAxNGJmMGE5YzMzZTg0ZGJkNmRjNmQzYTUyOGRlNDc5Zjg3Mzc3ZTJhZGM4NThjNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F8sTlNG_Kfo0ycT0-lNqL8Grxm826unQJmcLk-H5tf4)
> 
> 最新版本配置文件统一为 `yunzai/data/yuki-plugin/config/` 更新完重启后看看。旧的不会自动删除，只是不会读取它

感谢，已解决
