### ISSUE TITLE
希望增加检查频率，并且单独订阅直播不生效

### ISSUE THREAD

**Issue by lengxi-root** [snowtafir/yuki-plugin#7]
trssyunzai
单独订阅直播 不会推送，即使是执行#执行B站任务
订阅所有内容的话 #执行B站任务 会推送
但是不会自动推送
我将pushTime设置为 */1  * * * *  也没有效果
订阅数量较多时，#执行B站任务 没效果

**Comment by snowtafir** [comment]
指令不识别可以添加前缀 #优纪  。推送机制是定期检测，考虑到风控的问题，检测周期不应设置过短，而且，执行推送设置了随机延迟（避免风控问题）。

**Comment by lengxi-root** [comment]
指令会识别
推送机制，希望能给直播单独设置一个检查间隔，毕竟直播每次10分20分之后才会推。
风控问题，我不清楚你说的是qq还是b站
qq的话一般只有黑号或弱sign才会出现，
b站的话我之前用过千羽插件，千羽是1分钟检查一次
希望能增加关闭风控的配置选项

**Comment by snowtafir** [comment]
> 指令会识别 推送机制，希望能给直播单独设置一个检查间隔，毕竟直播每次10分20分之后才会推。 风控问题，我不清楚你说的是qq还是b站 qq的话一般只有黑号或弱sign才会出现， b站的话我之前用过千羽插件，千羽是1分钟检查一次 希望能增加关闭风控的配置选项

风控是B站那边控制的，怎么关？要实现单独1分钟检测一次需要换接口和大改，很麻烦，不想弄，什么时候闲得慌再考虑搞搞。还有，只要是2h内新开播的，没理由不推送（需要等十几秒执行）。按照开播偏好的时间点，设置好定期检测的时间，一般也不需要等太久

**Comment by lengxi-root** [comment]
> > 指令会识别 推送机制，希望能给直播单独设置一个检查间隔，毕竟直播每次10分20分之后才会推。 风控问题，我不清楚你说的是qq还是b站 qq的话一般只有黑号或弱sign才会出现， b站的话我之前用过千羽插件，千羽是1分钟检查一次 希望能增加关闭风控的配置选项
> 
> 风控是B站那边控制的，怎么关？要实现单独1分钟检测一次需要换接口和大改，很麻烦，不想弄，什么时候闲得慌再考虑搞搞。还有，只要是2h内新开播的，没理由不推送（需要等十几秒执行）。按照开播偏好的时间点，设置好定期检测的时间，一般也不需要等太久

关闭风控的配置的意思，是指添加个可以关闭(防止风控) 配置。
不需要你实现防止风控(一般是验证码)。只是需要有这个选项。(可以设置登录自己的号才能开)

**Comment by snowtafir** [comment]
> > > 指令会识别 推送机制，希望能给直播单独设置一个检查间隔，毕竟直播每次10分20分之后才会推。 风控问题，我不清楚你说的是qq还是b站 qq的话一般只有黑号或弱sign才会出现， b站的话我之前用过千羽插件，千羽是1分钟检查一次 希望能增加关闭风控的配置选项
> > 
> > 
> > 风控是B站那边控制的，怎么关？要实现单独1分钟检测一次需要换接口和大改，很麻烦，不想弄，什么时候闲得慌再考虑搞搞。还有，只要是2h内新开播的，没理由不推送（需要等十几秒执行）。按照开播偏好的时间点，设置好定期检测的时间，一般也不需要等太久
> 
> 关闭风控的配置的意思，是指添加个可以关闭(防止风控) 配置。 不需要你实现防止风控(一般是验证码)。只是需要有这个选项。(可以设置登录自己的号才能开)

没看懂你想表达什么，说到底B站的风控是识别到异常访问而被禁止，获取不到数据。插件设计上并没有显式的规避风控的配置，只是请求行为模拟为web端正常访问保持稳定而已。也用不到验证码（插件未实现该方式，而且不稳定容易似）。而且没有登录自己的号才是最需要保持规避风控的，不然没法用。关闭风控的配置，你是指直接请求动态数据的话，搁这追求不稳定？需要加快执行的话你自己改task部分的代码注释掉延迟部分就行了，快个5-8秒左右。

**Comment by lengxi-root** [comment]
> > > > 指令会识别 推送机制，希望能给直播单独设置一个检查间隔，毕竟直播每次10分20分之后才会推。 风控问题，我不清楚你说的是qq还是b站 qq的话一般只有黑号或弱sign才会出现， b站的话我之前用过千羽插件，千羽是1分钟检查一次 希望能增加关闭风控的配置选项
> > > 
> > > 
> > > 风控是B站那边控制的，怎么关？要实现单独1分钟检测一次需要换接口和大改，很麻烦，不想弄，什么时候闲得慌再考虑搞搞。还有，只要是2h内新开播的，没理由不推送（需要等十几秒执行）。按照开播偏好的时间点，设置好定期检测的时间，一般也不需要等太久
> > 
> > 关闭风控的配置的意思，是指添加个可以关闭(防止风控) 配置。 不需要你实现防止风控(一般是验证码)。只是需要有这个选项。(可以设置登录自己的号才能开)
> 
> 没看懂你想表达什么，说到底B站的风控是识别到异常访问而被禁止，获取不到数据。插件设计上并没有显式的规避风控的配置，只是请求行为模拟为web端正常访问而已。也用不到验证码（插件未实现该方式，而且不稳定容易似）。而且没有登录自己的号才是最需要保持规避风控的，不然没法用。关闭风控的配置，你是指直接请求动态数据的话，老实说对账号不太好，需要加快执行的话你自己改task部分的代码注释掉延迟部分就行了，快个5-8秒左右。

我的意思就是指(可以自行设置或缩短检测新内容的频率 比如直播或者动态)，这样可以更快拿到直播或者动态的新内容。
我这样说你懂了吧，就是你可以当做没有风控的这东西，我们可以随意设置，而不是写死插件里的。

**Comment by snowtafir** [comment]
> > > > > 指令会识别 推送机制，希望能给直播单独设置一个检查间隔，毕竟直播每次10分20分之后才会推。 风控问题，我不清楚你说的是qq还是b站 qq的话一般只有黑号或弱sign才会出现， b站的话我之前用过千羽插件，千羽是1分钟检查一次 希望能增加关闭风控的配置选项
> > > > 
> > > > 
> > > > 风控是B站那边控制的，怎么关？要实现单独1分钟检测一次需要换接口和大改，很麻烦，不想弄，什么时候闲得慌再考虑搞搞。还有，只要是2h内新开播的，没理由不推送（需要等十几秒执行）。按照开播偏好的时间点，设置好定期检测的时间，一般也不需要等太久
> > > 
> > > 
> > > 关闭风控的配置的意思，是指添加个可以关闭(防止风控) 配置。 不需要你实现防止风控(一般是验证码)。只是需要有这个选项。(可以设置登录自己的号才能开)
> > 
> > 
> > 没看懂你想表达什么，说到底B站的风控是识别到异常访问而被禁止，获取不到数据。插件设计上并没有显式的规避风控的配置，只是请求行为模拟为web端正常访问而已。也用不到验证码（插件未实现该方式，而且不稳定容易似）。而且没有登录自己的号才是最需要保持规避风控的，不然没法用。关闭风控的配置，你是指直接请求动态数据的话，老实说对账号不太好，需要加快执行的话你自己改task部分的代码注释掉延迟部分就行了，快个5-8秒左右。
> 
> 我的意思就是指(可以自行设置或缩短检测新内容的频率 比如直播或者动态)，这样可以更快拿到直播或者动态的新内容。 我这样说你懂了吧，就是你可以当做没有风控的这东西，我们可以随意设置，而不是写死插件里的。

我还以为你说的是啥呢，配置文件不就有？不过没有单个up或单个动态类型的。你设置的pushTime为 */1 * * * * 间隔太短，都没执行完成就又开始一轮了。。。。还有，你改的配置文件路径是哪里的？
