### ISSUE TITLE
功能建议：推送的图片长度自定义

### ISSUE THREAD

**Issue by CICILC** [snowtafir/yuki-plugin#9]
有些动态图片太长了 更改7500px后并没有任何效果 能否限制最大图片长度
![image](https://github.com/user-attachments/assets/944270a8-b528-4b3e-a7dc-0cc08adc0b75)
![image](https://github.com/user-attachments/assets/e283b483-bb67-411e-8755-0da402a7047a)
省略过长的文字即可

**Comment by snowtafir** [comment]
> 有些动态图片太长了 更改7500px后并没有任何效果 能否限制最大图片长度。。。。。。 省略过长的文字即可

更新，并把配置文件删除，重启bot再编辑配置文件项即可

**Comment by CICILC** [comment]
![Screenshot_20241009_073223_QQ](https://github.com/user-attachments/assets/b1efb94b-da6f-47dc-ab21-b3ef836feafb)
图片确实是缩短了 但是这个情况是什么个情况（滑稽）

**Comment by snowtafir** [comment]
图片确实是缩短了 但是这个情况是什么个情况（滑稽）
编程嘛，有Bug正常。已修。更新就行

**Comment by snowtafir** [comment]
> 图片确实是缩短了 但是这个情况是什么个情况（滑稽）

编程嘛，有Bug正常。已修。更新就行
